(()=>{
const screens={
 upload:'<div class="tool-document"><span>01 · UPLOAD</span><h4>Your existing documents.</h4><p>Grant objectives, field reports, meeting notes and finance summaries.</p></div><div class="preview-file"><b>PDF</b><span>Weekly outreach update<small>Field report · Sample document</small></span><i>Ready</i></div><div class="preview-file"><b>DOC</b><span>District health meeting<small>Meeting note · Sample document</small></span><i>Ready</i></div><div class="screen-note">The proposed workflow starts with a complete document, rather than new data entry for every observation.</div>',
 extract:'<div class="tool-document"><span>PDF · FIELD REPORT</span><h4>Weekly outreach update</h4><p>Illustrative document · Source linked</p></div><div class="tool-summary"><span>AI SUMMARY</span><p>Attendance may be improving following Saturday outreach. Stock availability remains a concern at two facilities.</p></div><div class="tool-signals"><div><b>Result signal</b><span>Attendance may have improved.</span></div><div><b>Decision</b><span>Outreach moved to Saturdays.</span></div><div><b>Risk</b><span>Stock issues at two facilities.</span></div><div><b>Evidence</b><span>CHW feedback and meeting notes.</span></div></div>',
 review:'<div class="tool-document"><span>03 · REVIEW</span><h4>Check the meaning against the source.</h4><p>Inspect the findings that need attention.</p></div><div class="screen-note"><small>RESULT SIGNAL</small><h4>Attendance may have improved.</h4><blockquote>“Attendance seems to have improved after moving outreach sessions to Saturdays.”</blockquote><p>The uncertainty is preserved. The source does not establish a measured increase or a causal effect.</p></div><div class="screen-note soft-note">Review the summary as needed. No sentence-by-sentence approval is required.</div>',
 connect:'<div class="tool-document"><span>04 · CONNECT</span><h4>Keep the evidence in context.</h4><p>Related records remain linked to their sources.</p></div><div class="preview-links"><div><small>INTENDED OUTCOME</small><b>Improve access to maternal care</b></div><div><small>RESULT SIGNAL</small><b>Attendance may have improved</b></div><div><small>RELATED DECISION</small><b>Saturday outreach sessions</b></div><div><small>FUNDING CONTEXT</small><b>Maternal health grant · Outreach allocation</b></div></div><div class="screen-note">Sources remain attached to each finding. Funding links describe program context, not transaction-level attribution or causation.</div>',
 use:'<div class="tool-document"><span>05 · USE</span><h4>One record for progress and outcome review.</h4><p>Reuse the evidence for reporting, evaluation and audit preparation.</p></div><div class="screen-note"><small>ILLUSTRATIVE EVIDENCE BRIEF</small><h4>Maternal care access</h4><p><b>Reported change:</b> Attendance may have improved after the outreach schedule changed.</p><p><b>Delivery risk:</b> Stock issues at two facilities.</p><p><b>Evidence gap:</b> The note does not include attendance counts.</p><p><b>Sources:</b> Weekly outreach update; CHW feedback reported in the note.</p></div><div class="screen-note soft-note">Teams remain responsible for interpretation and final reporting.</div>'
};const screen=document.getElementById('workflow-screen');if(!screen)return;const buttons=[...document.querySelectorAll('[data-preview]')];function show(key){screen.innerHTML=screens[key];buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preview===key)));}buttons.forEach(b=>b.addEventListener('click',()=>show(b.dataset.preview)));show('extract');
})();
